# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # define env
    env: 
      tech: "yaml"
      any: "anything"
    
    steps:
      - name: Super simples use case for environment variable
        run: |
          echo "The choose tech is $tech"
          echo "say... ${{env.any}}"
          echo "this repo variable is ${{ vars.TEST }}"
          
  using-environments:
   runs-on: ubuntu-latest
   environment:
    name: test_env
    
   steps:
    - name: uses environment variable 
      run: |
        echo "The super secret is ${{ vars.test_env.SUPER_SECRET }}"
